spring:
  cache:
    type: simple
  data:
    mongodb:
      database: test
      uri: mongodb://118.25.193.38:27017
  datasource:
    druid:
      url: jdbc:postgresql://118.25.193.38:5432/wanggoudan
      username: postgres
      password: Aa3800258
      driver-class-name: org.postgresql.Driver
      initial-size: 1
      max-active: 100
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      validation-query: SELECT 1
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      ##################################################
      # Spring监控配置，配置_Druid和Spring关联监控配置
      aop-patterns: cn.wanggoudan.repository.*
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: false
    # fix SQLFeatureNotSupportedException in LobCreatorBuilderImpl
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    # fix Hibernate Slow to Acquire Postgres Connection
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.jdbc.use_get_generated_keys: true
    show-sql: true
    hibernate.ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 4096Mb
      max-request-size: 40960Mb
server:
  port: 443
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  ssl:
    key-store: classpath:www.wanggoudan.cn.jks
    key-store-password: Aa3800258
    key-store-type: JKS
    key-alias: www.wanggoudan.cn